En este notebook vamos a hacer una simulación del mes de febrero con nuestra estimación de estaciones (y sus respectivos tamaños).

In [2]:
import pandas as pd

estaciones = pd.read_csv('centroides2.csv')
viajes = pd.read_csv('potenciales_viajes_cubiertos.csv')
tamaño_estaciones = pd.read_csv('tamaño_cluster.csv')

In [3]:
viajes.head()

,Unnamed: 0,idS,tsO,tsD,price,tt,dis,vel,lonO,latO,lonD,latD,duration_calc,clusterOrigen,clusterFinal,origin_lat,origin_lon,destination_lat,destination_lon
0,0,A0H4,2021-02-03 18:10:03,2021-02-03 18:17:44,2.1525,461,1715.336751,13.395254,12.466222,41.867388,12.470660,41.853908,461.0,174.0,122.0,NaN,NaN,NaN,NaN
1,1,A0H4,2021-02-13 18:21:13,2021-02-13 18:25:33,1.6500,260,1234.472044,17.092690,12.471143,41.923692,12.467502,41.934306,260.0,59.0,98.0,NaN,NaN,NaN,NaN
2,2,A0H4,2021-02-14 13:39:54,2021-02-14 13:48:03,2.2225,489,2221.481536,16.354465,12.467524,41.934342,12.486330,41.928270,489.0,98.0,137.0,NaN,NaN,NaN,NaN
3,3,A0H4,2021-02-14 14:37:53,2021-02-14 14:57:53,4.0000,1200,4562.843566,13.688531,12.486275,41.928301,12.457922,41.904302,1200.0,137.0,113.0,NaN,NaN,NaN,NaN
4,4,A0H4,2021-02-15 13:31:24,2021-02-15 13:34:45,1.5025,201,550.154792,9.853519,12.457876,41.904303,12.460773,41.907606,201.0,113.0,179.0,NaN,NaN,NaN,NaN

In [27]:
dia = 11
viajes_11 = viajes[(viajes['tsO'] > f'2021-02-{dia} 00:00:00') & (viajes['tsO'] < f'2021-02-{dia} 23:59:59')][['idS', 'tsO', 'tsD', 'price', 'clusterOrigen', 'clusterFinal']]
viajes_11['origen'] = viajes_11['clusterOrigen'].apply(lambda x: (estaciones[estaciones['cluster'] == x]['lat'].item(), estaciones[estaciones['cluster'] == x]['lon'].item()))
viajes_11['destino'] = viajes_11['clusterFinal'].apply(lambda x: (estaciones[estaciones['cluster'] == x]['lat'].item(), estaciones[estaciones['cluster'] == x]['lon'].item()))
viajes_11

,idS,tsO,tsD,price,clusterOrigen,clusterFinal,origen,destino
58,A0N7,2021-02-11 08:54:33,2021-02-11 09:19:03,4.6750,46.0,149.0,"(41.8773378, 12.5307418)","(41.9072608, 12.4732515)"
82,A0P6,2021-02-11 14:36:54,2021-02-11 14:48:43,2.7725,34.0,165.0,"(41.9119802, 12.4755149)","(41.9008112, 12.5000502)"
186,A2E3,2021-02-11 08:46:34,2021-02-11 09:01:14,3.2000,55.0,118.0,"(41.9319168, 12.5203835)","(41.9084313, 12.5028896)"
206,A2M3,2021-02-11 15:41:23,2021-02-11 15:53:13,2.7750,133.0,149.0,"(41.9049253, 12.4441233)","(41.9072608, 12.4732515)"
252,A2R1,2021-02-11 17:21:34,2021-02-11 17:43:24,4.2750,122.0,147.0,"(41.8573232, 12.4725779)","(41.8706408, 12.4684708)"
...,...,...,...,...,...,...,...,...
20200,Z8J1,2021-02-11 19:29:23,2021-02-11 19:36:43,2.1000,157.0,58.0,"(41.8462101, 12.4826066)","(41.845972, 12.4904363)"
20219,Z8Y2,2021-02-11 09:55:44,2021-02-11 10:02:53,2.0725,9.0,185.0,"(41.8827447, 12.5202617)","(41.8925043, 12.5092605)"
20260,Z9N9,2021-02-11 14:17:33,2021-02-11 14:42:04,4.6775,87.0,129.0,"(41.8875346, 12.5213157)","(41.8934018, 12.4871321)"
20287,Z9U3,2021-02-11 11:31:43,2021-02-11 11:39:53,2.2250,171.0,74.0,"(41.8861783, 12.5172333)","(41.8728698, 12.5279662)"
20288,Z9U3,2021-02-11 12:35:24,2021-02-11 12:50:24,3.2500,74.0,68.0,"(41.8728698, 12.5279662)","(41.8905524, 12.4946425)"